# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnnictEpgstationConnector < Formula
  desc "."
  homepage "https://mssn.dev/"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.3.0/annict-epgstation-connector_Darwin_x86_64.tar.gz"
      sha256 "680446902a1783aff04b481174b1ea460b6c942de7e0b8ef6af6df66a0acd54d"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.3.0/annict-epgstation-connector_Darwin_arm64.tar.gz"
      sha256 "2f71afee7800219132638beb4386292328485e45aa059619182dfc48b5dff7e1"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.3.0/annict-epgstation-connector_Linux_arm64.tar.gz"
      sha256 "cdc0998d921355237b8ed7e6a3fee5e45f33d043063c2e590b48b3e6192bc3d8"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.3.0/annict-epgstation-connector_Linux_x86_64.tar.gz"
      sha256 "5bdf1107409819bff732e8ad81ecd8962fe232582f8b85dab82c577b9f1901e1"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
  end

  test do
    system "#{bin}/annict-epgstation-connector -h"
  end
end
