# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnnictEpgstationConnector < Formula
  desc "."
  homepage "https://mssn.dev/"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.0.7/annict-epgstation-connector_Darwin_arm64.tar.gz"
      sha256 "1b9bd3bdfe5c804e552b7c38fabfc3ad12e474444d614dc4103ae4231a4dd9cc"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.0.7/annict-epgstation-connector_Darwin_x86_64.tar.gz"
      sha256 "b1b498a3081e5e7a9828434ff2caf14a40e8c7a2c99d5b6d7401fc97cbcfa983"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.0.7/annict-epgstation-connector_Linux_x86_64.tar.gz"
      sha256 "8eaa21a022f9b4f63ffb9c49a872be65cff63da04b47c96afa680d9e6e57ad8a"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/musaprg/annict-epgstation-connector/releases/download/v0.0.7/annict-epgstation-connector_Linux_arm64.tar.gz"
      sha256 "cd89dc17b8e10acde833c22dd7c636955b7c59fdd78572d6fe8fee2d8be9ff21"

      def install
        bin.install "annict-epgstation-connector"
      end
    end
  end

  test do
    system "#{bin}/annict-epgstation-connector -h"
  end
end
