# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultipassZigDevenv < Formula
  desc "Generating multipass-based development environment for Zig project."
  homepage "https://mssn.dev/"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/musaprg/multipass-zig-devenv/releases/download/v0.0.2/multipass-zig-devenv_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "35a09a4329dda991479ad8ff3f86c8c20c2c532ee65bba14924b076d9367d230"

      def install
        bin.install "multipass-zig-devenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/musaprg/multipass-zig-devenv/releases/download/v0.0.2/multipass-zig-devenv_0.0.2_Darwin_arm64.tar.gz"
      sha256 "d2444d3efa892782b12ebdef497a5c7e0d38bfe6912bde7f291a30e6acbd65ee"

      def install
        bin.install "multipass-zig-devenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/musaprg/multipass-zig-devenv/releases/download/v0.0.2/multipass-zig-devenv_0.0.2_Linux_x86_64.tar.gz"
      sha256 "690f55b15e55d7adfd572eb67d6181dc11aa2b2dd75a60290573a54ed9f22e90"

      def install
        bin.install "multipass-zig-devenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/musaprg/multipass-zig-devenv/releases/download/v0.0.2/multipass-zig-devenv_0.0.2_Linux_arm64.tar.gz"
      sha256 "2032108c33b43e2cf40c38e84f6f30d360de1b77d404dd95afd2054f7e886950"

      def install
        bin.install "multipass-zig-devenv"
      end
    end
  end

  test do
    system "#{bin}/multipass-zig-devenv -h"
  end
end
